name: Release
permissions:
  contents: read

on:
  release:
    types: [ published ]

jobs:
  validate-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Run full test suite
      run: |
        pytest tests/ -v

    - name: Validate examples
      run: |
        python examples/example_usage.py
        python examples/distributed_rank_aware_generation.py
        python examples/batch_processing_strategies.py
        python examples/benchmark_performance_profiling.py

    - name: Check package build
      run: |
        pip install build
        python -m build
        
    - name: Validate version consistency
      run: |
        python -c "
        import tomllib
        with open('pyproject.toml', 'rb') as f:
            data = tomllib.load(f)
        version = data['project']['version']
        tag = '${{ github.event.release.tag_name }}'
        expected = f'v{version}'
        assert tag == expected, f'Tag {tag} does not match version v{version}'
        print(f'✓ Version {version} matches tag {tag}')
        "